services:
    redis:
      image: redis:7
      restart: always

      command: >
        redis-server
        --requirepass ${REDIS_PASSWORD}
        --maxmemory-policy noeviction

      ports:
        - "6379:6379"

      volumes:
        - redis_data:/data

      healthcheck:
        test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
        interval: 5s
        timeout: 5s
        retries: 10

      networks:
        - ghostdoc

networks:
  ghostdoc:
    external: true
volumes:
  redis_data:
