services:
    langfuse-worker:
      image: docker.io/langfuse/langfuse-worker:3
      restart: always

      depends_on:
        postgres:
          condition: service_healthy
        minio:
          condition: service_healthy
        redis:
          condition: service_healthy
        clickhouse:
          condition: service_healthy

      environment:
        NEXTAUTH_URL: http://localhost:3000

        DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@$postgres:5432/${POSTGRES_DB}

        NEXTAUTH_SECRET: mysecret
        SALT: mysalt

        ENCRYPTION_KEY: 9f7f5db6a8d4a2b2d0d9a7f7d4f9f8f9b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1

        TELEMETRY_ENABLED: "true"

        CLICKHOUSE_URL: http://clickhouse:8123
        CLICKHOUSE_MIGRATION_URL: clickhouse://${CLICKHOUSE_USER}:${CLICKHOUSE_PASSWORD}@clickhouse:9000/${CLICKHOUSE_DB}

        CLICKHOUSE_USER: ${CLICKHOUSE_USER}
        CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
        CLICKHOUSE_DB: ${CLICKHOUSE_DB}
        CLICKHOUSE_CLUSTER_ENABLED: "false"

        REDIS_HOST: redis
        REDIS_PORT: 6379
        REDIS_AUTH: ${REDIS_PASSWORD}

        LANGFUSE_S3_EVENT_UPLOAD_BUCKET: langfuse
        LANGFUSE_S3_EVENT_UPLOAD_REGION: auto
        LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
        LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
        LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT: http://minio:9000
        LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE: "true"
        LANGFUSE_S3_EVENT_UPLOAD_PREFIX: events/

        LANGFUSE_S3_MEDIA_UPLOAD_BUCKET: langfuse
        LANGFUSE_S3_MEDIA_UPLOAD_REGION: auto
        LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
        LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
        LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT: http://minio:9000
        LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE: "true"
        LANGFUSE_S3_MEDIA_UPLOAD_PREFIX: media/

      ports:
        - "3030:3030"

      networks:
        - ghostdoc

networks:
  ghostdoc:
    external: true
